# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fresh repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Send Codecov jacoco results
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
          flags: unittests
          name: codecov-jacoco
          fail_ci_if_error: true

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fresh repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install gpg secret key
        run: |
          echo ${{ secrets.GPG_SECRET_KEY }} | base64 --decode | gpg --batch --import

      - name: Export gpg secret key to old format
        run: |
          gpg --export-secret-keys \
            --pinentry-mode=loopback \
            --passphrase ${{ secrets.SIGNING_PASSWORD }} \
            --output ~/.gnupg/secring.gpg

      - name: Publish with Gradle
        run: |
          export SIGNING_FILE=$(echo ~/.gnupg/secring.gpg)
          ./gradlew publish \
            -P signing.keyId=${{ secrets.SIGNING_ID }} \
            -P signing.password=${{ secrets.SIGNING_PASSWORD }} \
            -P signing.secretKeyRingFile=$SIGNING_FILE \
            -P ossrhUsername=${{ secrets.OSSRH_USERNAME }} \
            -P ossrhPassword=${{ secrets.OSSRH_PASSWORD }}
